<?php
define('_MORE', 'More info &raquo;');
define('_FILE_CLICKS', 'Clicks');
define('_INSTRUCTION', 'Installation Instructions');
define('_VIEWS', 'Views');
define('_DATA', 'Date');
define('_TOP_TITLE', '<strong>Push Notifications</strong><br> for your sites for free');
define('_SITES_STAT', 'Sites statistic');
define('_ADS_STAT', 'Ads statistic');
define('_BALANCE', 'Balance');
define('_CHOOSESECTION', 'Select the desired section in the left menu');
define('_NOTHINGFOUND', 'Nothing found');
define('_SECTIONS', 'Sections');
define('_SECTIONPAGES', 'Pages in the section');
define('CONTACTS', 'Contacts');
define('REGISTERGO', 'Sign up');
define('BLOCKTEXT', 'Click "Allow" to continue browsing the site.');
define('SUBSCRIBETHANKS', 'Thanks for subscribing! You will now be redirected to the link.');
define('DESCRIPTION', 'Collect push subscriptions and earn them smartly! 3 monetization options for push subscribers, high earnings!');
define('TITLE', 'Monetize your push subscribers into money');
define('HOME', 'Home');
define('ADVANTAGES', 'Advantages');
define('CONDITIONS', 'Conditions');
define('STATISTIC', 'Statistics');
define('FAQ', 'Questions and answers');
define('NEWS', 'News');
define('LOGIN', 'Sign in');
define('SHORTDESCR', 'Join our network for push sendings, traffic exchange and earning on subscriptions');
define('REGISTER', 'Registration');
define('OURADVANTAGES', 'Our advantages');
define('OURADVANTAGES_TEXT', 'Check out the features of the system');
define('ADVANTAGES_1', 'Four options for collecting subscriptions. For https and http sites.');
define('ADVANTAGES_2', 'Landings, Redirect and Iframe links for traffic arbitration');
define('ADVANTAGES_4', 'Creating your own landing pages and copying existing ones in one click.');
define('ADVANTAGES_5', 'Detailed statistics on 12 types up to each sending.');
define('ADVANTAGES_6', 'Sending your ads to 15 targeting conditions.');
define('ADVANTAGES_7', 'Over 90 thousand ready-made promotional materials collected from affiliate networks.');
define('ADVANTAGES_8', 'Individual settings for push notifications.');
define('ADVANTAGES_9', 'Exchange traffic, do sending on partner bases.');
define('CPC', 'Pay per click');
define('HOWITWORKS', 'How it works ?');
define('HOWITWORKS_1', 'Register.');
define('HOWITWORKS_2', 'Add a site or landing page.');
define('HOWITWORKS_3', 'Get the code to install on the site or a link to send traffic, for which users subscribe.');
define('HOWITWORKS_4', 'You can also connect ad network feeds to make money on clicks.');
define('HOWITWORKS_5', 'You can allow other users to send ads to your database with pay-per-click.');
define('HOWITWORKS_6', 'Exchange push traffic with other sites you connect to.');
define('SYSSTAT', 'System statistics');
define('SYSSTATDESCR', 'Statistics on subscriptions and sending for the day');
define('ALLUSERS', 'Total Users');
define('ALLSUBS', 'Total Subscribers');
define('NEWSUBS', 'New for today');
define('SENDED', 'Sending for today');
define('NEWS', 'Project news');
define('SUBSCRIBE', 'Subscribe to our newsletter <br>to find out about updates.');
define('BUYSEND', 'You can place your ad on this audience <span> from $0.005 per click </span> on your push message');
define('FAQ_DESCR', 'We have collected for you the most frequently asked questions with answers to them.');
define('GETSTARTED', 'Subscribe');
define('YOURMAIL', 'Your email');