<?php
define('_AOPTIONS', 'System settings');
define('_USER_UPDATED', 'User updated');
define('_GOOD_USER', 'Secure user');
define('_SECURITY5', 'Number of detected to block');
define('_SECURITY4', 'Block IP');
define('_SECURITY3', 'Block user');
define('_SECURITY2', 'Send notification when detected');
define('_SECURITY1', 'Check incoming requests');
define('_SECURITY', 'Security');
define('_CITY_CHECK', 'Check the city at the login');
define('_CLOSE_SENDING', 'Disallow  sending');
define('_REF_PROGRAM', 'Referral program');
define('_ISCHECKED', 'checked');
define('_USER_EDIT', 'User edit');
define('_GSECRET', 'The secret key');
define('_INSTALLSYSTEM', 'System installation');
define('_ADD_MACROS', 'Add macros');
define('_COMMONS', 'Common');
define('_SYS_LANGS', 'Languages');
define('_EXCHANGE_MIN', 'Min. subscribers for traffic exchange');
define('_NS_DOMAIN', 'NS domains');
define('_ALLOW_DOMAINS', 'Allow domain binding');
define('_REFERAL_MUAL', 'Manual activation of referral');
define('_ALLOW_COPYLAND', 'Allow to copy landing pages to users');
define('_AAOPTIONS16', 'Feed tamplates');
define('_AAOPTIONS15', 'Translations');
define('_AAOPTIONS14', 'Sites category');
define('_AAOPTIONS13', 'Feed templates');
define('_AAOPTIONS12', 'Language macros');
define('_AAOPTIONS11', 'Feed fees');
define('_AAOPTIONS10', 'Domain for pictures');
define('_AAOPTIONS9', 'Forbidden IP');
define('_AAOPTIONS8', 'Captcha at login');
define('_AAOPTIONS7', 'Captcha at registration');
define('_AAOPTIONS6', 'Approve email');
define('_AAOPTIONS5', 'Allow registration');
define('_AAOPTIONS4', 'Accounts');
define('_AAOPTIONS3', 'Allow traffic exchange');
define('_AAOPTIONS2', 'Allow sending');
define('_AAOPTIONS1', 'System Email');
define('_COMMON', 'Common');
define('_FEEDS_TEXT8', 'ID not found');
define('_FEEDS_TEXT7', 'No feed ads received!');
define('_FEEDS_TEXT6', 'Available ads');
define('_FEEDS_TEXT5', 'Sendings, views, clicks');
define('_FEEDS_TEXT4', 'OS, browser, lang');
define('_FEEDS_TEXT3', 'Information about subscriber');
define('_FEEDS_TEXT2', 'Subscriber ID');
define('_FEEDS_TEXT1', 'Feeds test');
define('_ANALIT_TEXT21', 'Prices by regions');
define('_ACTION', 'action');
define('_THEPAGE', 'Page');
define('_IFRAMEOPTIONS3', 'Do not pass by link');
define('_GET_WITHDR', 'Get withdrawals');
define('_CRON', 'cron');
define('_ALLOW_OPTIONS_TOOLTIP', 'Allow users to specify their own individual sending settings that are different from the current');
define('_ALLOW_OPTIONS', 'Allow sending options');
define('_ALLOW_ACCTOUNTS_TOOLTIP', 'Allow all users to create guest accounts, or only to admins');
define('_ALLOW_ACCTOUNTS', 'Allow creating guest accounts');
define('_FPROC_TOOLTIP', 'The commission that you take away from the click price');
define('_MINSUMMA_TOOLTIP', 'Minimum amount for order payment');
define('_SORTTYPE_TOOLTIP', 'Algorithm for sorting ads. Choose the one that is better in profitability');
define('_UNSUBSPROC_TOOLTIP', 'The percentage of unsubscribes from the sending, upon reaching which, to block the ad. 0 - 100');
define('_BLOCKUNSUBS_TOOLTIP', 'If users unsubscribe from some ads more often, then you can block them');
define('_STPWRDS_TOOLTIP', 'Words, that is need to block in ads');
define('_TSTID_TOOLTIP', 'Subscriber ID, which you can get from the Statistics - Subscribers page');
define('_TST_TOOLTIP', 'Enable the push test, below write the id of the subscriber for whom to do the notification');
define('_FRBSCONF_TOOLTIP', 'This is a piece of code from the General Settings tab. Begin with - var firebaseConfig');
define('_SRVKEY_TOOLTIP', 'This is the server key that you can get at https://firebase.google.com/ in the project settings, tab Cloud Messaging');
define('_MINBID_TOOLTIP', 'The minimum price for feeds at which auction ads will be taken');
define('_LANDDOMAIN_TOOLTIP', 'This domain is used for links to landing pages.');
define('_JSDOMAIN_TOOLTIP', 'This domain is used for JS codes for sites');
define('_PUSHDOMAIN_TOOLTIP', 'This domain is used for links in push notifications.');
define('_TRNKDESCR_TOOLTIP', 'Trim the length of the description from the feeds to the specified limit. It is not recommended to change.');
define('_TRNKTITLE_TOOLTIP', 'Trim the length of the title from feeds to specified limit. It is not recommended to change.');
define('_TIMEVAL_TOOLTIP', 'The lifetime of push during which the subscriber can receive it. If the time is up, the user will not receive a notification');
define('_SENDLIMIT_TOOLTIP', 'Split push sending to the specified number, to optimize the load for large volumes');
define('_IMAGESND_TOOLTIP', 'Send a large image for ads, or just a small one for all feeds.');
define('_CHECKURL_TOOLTIP', 'When clicking on the link, check the server’s response, if the server answered with an error, the feed will be disabled. This can help avoid unpaid clicks if the affiliate network is unavailable..');
define('_DNTSENDAFTRCL_TOOLTIP', 'Do not resend one ad after clicking on it');
define('_SENDINGPUSH_TOOLTIP', 'Enable push sending');
define('_RECAPTCHA_TOOLTIP', 'To get these parameters go to https://www.google.com/recaptcha');
define('_BLACKIP_TOOLTIP', 'Deny the specified ip access to the admin panel. Each from a new line.');
define('_LOGCAPTCHA_TOOLTIP', 'Display captcha at login. To work, specify the settings below Google');
define('_REGCAPTCHA_TOOLTIP', 'Display captcha at registration. To work, specify the settings below Google');
define('_EMAILCONFIRM_TOOLTIP', 'After registration, require a confirmation email for login');
define('_REGISTERON_TOOLTIP', 'Allow self-registration of users');
define('_LANGS_TOOLTIP', 'Available system languages');
define('_DOMAINNS_TOOLTIP', 'NS domains to which to bind domains');
define('_EXCHMIN_TOOLTIP', 'Minimum site subscribers to participate in traffic exchange');
define('_ALLOWDOMAINS_TOOLTIP', 'Allow adding users their domains for use in links. To work, you will also need to configure a server to automatically generate SSL for bound domains.');
define('_REFACTIVE_TOOLTIP', 'Each user to activate the ref link individually');
define('_ALLOWREF_TOOLTIP', 'Activate referral program');
define('_COPYL_TOOLTIP', 'Allow users to copy external pages as landing pages');
define('_TREX_TOOLTIP', 'Allow users to share traffic');
define('_SENDING_TOOLTIP', 'Allow users to send notifications to their subscribers');
define('_FEED_TIMEOUT_TOOLTIP', 'If the feed responds to the request for more than the specified time, then it is disconnected from the auction for an hour');
define('_FEED_TIMEOUT', 'Feed timeout');
define('_AGREE_RULES', 'I agree with the project rules');
define('_PAYM_NOUSER', 'There are no users to add');
define('_PAYM_ADDED', 'Added to payout list');
define('_SUPER_ADM_TOOLTIP', 'Super admin has access to all sections of the site. But for management must be under the role ADMIN');
define('_IS_SUPPORT', 'Bind super admin as support for users. Support contacts will be displayed in the sidebar');
define('_ADMIN_FUNC', 'Admin func');
define('_SECTIONS', 'Sections');
define('_WEEK_DIFF', 'difference from last week');
define('_FOR_WHO', 'For who');
define('_SEND_VIEWS', 'Views');
define('_SEND_ERROR', 'With errors');
define('_CREATED', 'Created');
define('_SENDING_TEXT9', 'Sending time');
define('_SENDING_TEXT8', 'user login');
define('_SENDING_TEXT7', 'promo');
define('_SENDING_TEXT6', 'Get');
define('_SENDING_TEXT5', 'Receivers');
define('_SENDING_TEXT3', 'Sites from');
define('_SENDING_TEXT2', 'Balance from');
define('_SENDING_TEXT1', 'Get recipients');
define('_SENDING1', 'sending');
define('_GET_WITHDR', 'Receive payouts');
define('_ALLMONEY', 'All money');
define('_WEEK', 'Week');
define('_MONEYIN', 'Earned');
define('_ALLOW_REFERAL', 'Allow referals');
define('_AUTOMONEY', 'Automatic withdrawal');
define('_GET_PROMO_MAIL', 'Get promo mails');
define('_GET_MAIL', 'Get mails');
define('_USER_OWNER', 'Account owner');
define('_MORE_INFO', 'More info');
define('_ACCOUNT_ENTER', 'Enter account');
define('_FROM_NETWORK', 'From network');
define('_DOUBLEIP', 'IP repeat');
define('_CONTACTS', 'Contacts');
define('_ANY', 'Any');
define('_SORTFORM', 'Sort');
define('_REASON', 'Reason');
define('_NOPAY_CLICKS', 'Unpaid clicks');
define('_ADMIN_CONF', 'Admin config');
define('_RESETERROR', 'Reset errors');
define('_LAUNCH', 'Launch');
define('_CRON', 'cron');
define('_LAUNCH_LOG', 'Launch log');
define('_COMPLETE', 'Complete');
define('_LAST_LAUNCH', 'Last launch');
define('_AVGTIME', 'Avg time');
define('_ERRORS', 'Errors');
define('_LAUNCHED', 'Launched');
define('_FREQUENCY', 'Frequency');
define('_LOCATION', 'Location');
define('_BY_USERS', 'By users');
define('_JOURNAL', 'Journal');
define('_COMMON_STAT', 'Total stats');
define('_ANALYTICS', 'Analytics');
define('_CRONS', 'Crons');
define('_APPROVE_NEW_PLACE', 'Confirmation of login from a new place by email');
define('_UNDER_LOGIN', 'You are a user');
define('_ALL_NOTIF', 'See all notifications');
define('_GROUP_MACROS', 'ad group name');
define('_ADD_UTM', 'put tags in the link for GA & YM');
define('_ADS_CONDITION', 'Ad Terms');
define('_MONEYCPA_TOOLTIP', 'Information about earnings received through postback, provided that the currency is posted correctly, earnings excluding rejected actions');
define('_MONEYSPENT_TOOLTIP', 'The expense is displayed with daily limits and total, if they were specify for the ad');
define('_CONV_TOOLTIP', 'Information about conversions that you submitted through the postback link');
define('_YESTERDAY', 'Yesterday');
define('_ADD_COMMENT', 'Add comment');
define('_SEE_EXAMPLE', 'See an example of the format');
define('_NEW_CITY_APPROVED', 'New location confirmed');
define('_NEW_CITY_ENTER', 'Login to the account from a new place, confirmation by email is required, expect an email');
define('_MAY_LOGIN', 'You can log in to your account.');
define('_EMAIL_NEED_CONFIRM', 'A message was sent to your email, follow the link from the letter to enter your account');
define('_IP_BLOCKED', 'Access to account is blocked');
define('_CONFIRM_MAIL_ERR', 'To enter your account you need to confirm your email. Check your inbox, if the message is spam, then mark it as “not spam” to receive messages from us.');
define('_CONFIRM_MAIL', 'To activate your account, follow the link');
define('_REGISTER_OFF', 'Registration of new accounts is temporarily disabled. For details, please contact by email');
define('_MODULE_OFF', 'This section is disabled or is being finalized, please contact support for details.');
define('_FILENAME', 'name of file');
define('_MOPERATOR', 'Name of mobile operator');
define('_PARAMETERS', 'Parameters');
define('_GET_PUSH_NOTIF_TOOLTIP', 'If you subscribed to site notifications, you can receive system notifications in the browser, or disable them');
define('_GET_PUSH_NOTIF', 'Receive push notifications');
define('_GET_TELEG_NOTIF', 'Receive notifications in Telegram');
define('_TE_INFO', 'In this section you can add your offer for traffic exchange. Only sites with more than 100 subscribers can participate in the exchange. After creating the offer, anyone will be able to send you an exchange request and you will only have to confirm or decline the application. If you have accepted the request, then you will be able to do mutual sendings to your subscribers subject to the set limit for sending and the difference in the number of subscribers.');
define('_TE_DELETED', 'Offer deleted');
define('_TE_ERR_DEL', 'It is not possible to delete an offer with active exchange requests; first, you must cancel active requests');
define('_DENY_ADS', 'Due to a policy violation, you can no longer add ads');
define('_DENY_SENDING', 'Due to a policy violation, you can no longer add newsletters');
define('_WAYBLOCK_008', 'newsletter advertising');
define('_MY_SEND_INFO', 'This section is intended for sending push on your and affiliate subscriptions about updating sites. Only newsletters, any advertising is FORBIDDEN!');
define('_EXCHANGE_TOOLTIP_6', 'Conversion rate for recieved push');
define('_EXCHANGE_TOOLTIP_5', 'Conversion rate for sent push');
define('_EXCHANGE_TOOLTIP_4', 'How much clicks did your push followers do');
define('_EXCHANGE_TOOLTIP_3', 'How many sending are made for your subscribers');
define('_EXCHANGE_TOOLTIP_2', 'How many clicks you received from your sending');
define('_EXCHANGE_TOOLTIP_1', 'How many sending  you  have made to partners bases');
define('_IS_SITE', 'This site already exists');
define('_NOT_NECESSERY', 'Not necessary');
define('_EXCHANGE_TITLE_URL', 'Traffic exchange');
define('_CTR_OUT', 'CTR Out');
define('_CTR_IN', 'CTR In');
define('_TRAF_EXCH_CLICKS_OUT', 'Clicks Out');
define('_TRAF_EXCH_CLICKS_IN', 'Clicks In');
define('_TRAF_EXCH_SENDED_IN', 'Sending In');
define('_TRAF_EXCH_SENDED_OUT', 'Sending Out');
define('_TRAF_EXCH_TITLE', 'Traffic exchange statistics');
define('_TRAF_EXCH_CLOSED2', 'Exchange between URLS sites has been canceled');
define('_TRAF_EXCH_CLOSED', 'Exchange between URLS sites has been canceled by the site owner');
define('_TRAF_EXCH_STOP1', 'You can’t cancel the exchange on which you made more sending than you received!');
define('_TRAF_EXCH_STATS', 'Exchange statistics');
define('_TRAF_EXCH_APPROVE', 'Traffic exchange request confirmed');
define('_TRAF_EXCH_MAXSEND_TOOLTIP3', 'How many sending per day can a site do for your subscribers. The limit is calculated automatically based on your limit, the number of subscribers to the site and their effectiveness. How much is done today.');
define('_DENY', 'Decline');
define('_APPROVE', 'Approve');
define('_PARTNER_SITE', 'Affiliate website');
define('_OFFERS_ALL', 'Total offers');
define('_OFFER_PLAY', 'Status changed, exchange requests resumed');
define('_OFFER_PAUSE', 'Status changed, new applications are no longer accepted');
define('_TODAY', 'Today');
define('_EXCH_STAT', 'Exchange statistics');
define('_TRAF_EXCH_STAT_INFO', 'Statistics of sending lists for site subscribers for 7 days');
define('_TRAF_EXCH_MAXSEND_TOOLTIP2', 'The number of sending  per day that the site owner allowed and how much has been done today');
define('_EFFECT', 'Efficiency');
define('_INSTRUCTION', 'Installation Instructions');
define('_SITE_CATEGORY_INFO', 'Correctly specified site category is important in traffic exchange');
define('_TRAF_SEND_REQUEST_JOUR', 'Exchange request sent');
define('_TRAF_SEND_REQUEST_SENDED', 'Exchange request sent! As soon as the sub-partner confirms the application, you will be able to make sending by his base, and it will be according to yours, taking into account the set limits.');
define('_TRAF_SEND_REQUEST_INFO', 'The request can be sent only for sites with more than 100 active subscribers');
define('_TRAF_SEND_REQUEST2', 'Send exchange request');
define('_TRAF_SEND_REQUEST', 'SEND REQUEST');
define('_TRAF_MAX_SEND_WARN', 'The number of sending can be changed once a day');
define('_REPEAT_INSERT_ERR', 'An error occurred while re-recording!');
define('_TRAF_EXCH_INFO', 'You can choose only sites for traffic exchange with more than 100 subscribers.');
define('_TRAF_EXCH_NEWUPD', 'Add or update offer');
define('_TRAF_EXCH_UPD', 'Offer updated');
define('_TRAF_EXCH_CREATED', 'Exchange offer created');
define('_TRAF_EXCH_WARN1', 'You need to specify the maximum number of sending for your subscribers per day');
define('_TRAF_EXCH_NO_SITES', 'No sites for exchange');
define('_TRAF_EXCH_MAXSEND_TOOLTIP', 'Specify how many maximum sending for your subscribers can do per day, this value also affects how much you will be able to make sending to partner bases');
define('_TRAF_EXCH_SITES', 'Choose a site');
define('_TRAF_EXCH_NEW', 'Add offer');
define('_TRAF_EXCH_ADMINS', 'Are exchanged');
define('_TRAF_EXCH_MY', 'Exchange requests');
define('_TRAF_EXCH_LIST', 'Exchange offers');
define('_TRAF_EXCH', 'Web traffic exchange');
define('_SITE_PLUGINS_INFO', 'Plugins and extensions allow you to conveniently send push from your CMS or directly from your browser. Select the needed plugin from the list and follow the installation instructions.');
define('_SITE_PLUGINS', 'Plugins and Extensions');
define('_FILE_ERR', 'No such file!');
define('_FILE_CLICKS', 'Clicks');
define('_FILE_LOADS', 'Downloads');
define('_SEND_LOOP_INFO', 'This option activates the sending until the user sees the message, repeats up to 6 times with a pause of 4 hours');
define('_SEND_LOOP', 'Send until view');
define('_RESETTIME_OK', 'Next sending time was reset to current');
define('_RESETTIME', 'Reset time');
define('_PAYTYPE_SEL', 'Payment type');
define('_CODETEXT31', 'URL to which the user will be redirected after blocking subscribing');
define('_CODETEXT30', 'URL to which the user will be redirected after subscribing');
define('_BLOG', 'Articles');
define('_ISMAIL', 'This email is already in use');
define('_SUBSID_INFO', 'Specify with a comma. Under this condition, the remaining conditions do not apply.');
define('_SUBSID', 'Subscribers ID');
define('_VIEWS2', 'views');
define('_LAND_SORT2', 'popular first');
define('_LAND_SORT1', 'new first');
define('_TITLES', 'Titles');
define('_PRELAND', 'Prelending');
define('_SEND_PUSH', 'Send push');
define('_STOP_WORDS_INFO', 'Stop words with a comma, verification is carried out including by ad URL');
define('_BLOCK_CATEG', 'Deny categories');
define('_MACROS_TAG', 'User tag');
define('_SITE_EMPTY', 'Add your first site or landing page to get a code or link for collecting subscribers.');
define('_SITE_URL_WRONG', 'The URL is incorrect');
define('_GET_LINK_INFO', 'In addition, you can specify parameters in the links: <br> <b>subid</b> - source ID <br> <b>tag</b> - user tag, for example, category or subject of the traffic source <br> <b>price</b> - click price for calculating profits in our statistics <br> <b>text</b> - text on the lock screen <br> You can bind your domain in the settings.');
define('_GET_LINK_3', 'In this link you replace your site instead of the URL and then the user can get to it only after subscribing.');
define('_GET_LINK_2', 'In this link you can replace your site for the URL (only HTTPS!) And then access to it will be closed through subscription.');
define('_GET_LINK_1', 'Landing link for subscribing users, use this link to send traffic to it, in the landing settings you can choose ready-made system landing pages, either create your own or copy another landing page.');
define('_GET_LINK', 'Get link');
define('_AVAIL_EXCHANGE', 'Sold on the exchange of subscribers');
define('_CREATIV_FOUND', 'Creatives found for the specified domain: X pcs');
define('_CAGENT', 'Counterparty');
define('_SITES_TARGET', 'In parentheses are the number of subscribers');
define('_WAYBLOCK_007', 'site unavailable or wrong link');
define('_SEND_MODERATESTATUS', 'Sending status changed');
define('_SEND_COPY', 'Copy ad');
define('_SEND_FAIL', 'There are no subscribers for the specified mailing conditions, use the check to get information about the number of available subscribers.');
define('_SEND_FINISH', 'Completed');
define('_SEND_MODER', 'On check');
define('_SEND_STOP', 'Stopped');
define('_SEND_NOW', 'Sent out');
define('_SEND_WAIT', 'Expected to launch');
define('_START', 'Start');
define('_STOP', 'Stop');
define('_SEND_UNSUBS_TOOLTIP', 'Number of unsubscribers before sending');
define('_SEND_UNSUBS', 'Unsubscribed');
define('_SEND_RECIEVE', 'Subscribers');
define('_SEND_UPDATE', 'Sending updated');
define('_SEND_ADDED', 'Sending created');
define('_NEED_URL', 'Enter a link');
define('_EDIT_SEND', 'Edit sending');
define('_FAST_SEND_TIME', 'Time sending');
define('_FAST_SEND_MACROS1', 'id sending');
define('_CREATE_SEND', 'Create sending');
define('_FAST_SEND', 'Send push');
define('_SITESBLOCKEDADS', 'Selected sites / subid were blocked for ads');
define('_BLOCK_ADS', 'Block for ads');
define('_BLOCK_ACCOUNT', 'Block for account');
define('_BLOCK_SUBIDS', 'Block Subid');
define('_BLOCK_SITES', 'Block sites');
define('_PAY_VIEWS', 'Payed ads views');
define('_DIS_ADBLOCK', 'For the site to work correctly, add the site to the white list of extensions Adblock, Ghostery, AdGuard');
define('_SEND_ME_TOOLTIP', 'If you subscribed to site alerts, you can check how the ad will look in the browser');
define('_SEND_ME', 'send me push');
define('_MINIMAL_VAL', 'Minimal value');
define('_RECOMENDED', 'Recomended');
define('_LOW', 'low');
define('_MIDDLE', 'average');
define('_HIGHT', 'high');
define('_DEMAND', 'Demand');
define('_REGIONS_COMPETITORS_INFO', 'List of major regions and traffic demand for them, as well as average prices for CPC and CPM');
define('_REGIONS_COMPETITORS', 'Demand by Region');
define('_GROUP_DELETE', 'All related ads will also be deleted');
define('_GROUP_DELETED', 'group and all related ads deleted');
define('_NEW_PASS_ERR', 'You can no longer send password reset requests today.');
define('_PASS_CHANGED', 'Password changed successfully');
define('_CODE_ERROR', 'The code is incorrect or the request is no longer relevant');
define('_GET_NEW_PASS_MAIL', 'Password change link sent to email.');
define('_USER_NOTFOUND', 'User is not found');
define('_LOGININ', 'Login');
define('_GET_NEW_PASS', 'Password recovery');
define('_FORGET_PASS', 'Forgot password?');
define('_BUYED_SUBS', 'Buying subscribers on the exchange at your request for the amount of');
define('_SELLED_SUBS', 'Your subscribers have been bought on the exchange for the amount of');
define('_ADS_BLOCKED_INFO', 'The graph displays the number of declined auctions with the ad targeting.');
define('_INFO', 'Information');
define('_DECLINED', 'Declined');
define('_APPROVED', 'Approved');
define('_CPA_NETWORK', 'Affiliate network');
define('_TIME_AFTER_CLICK', 'Time after click');
define('_POSTBACK_LOG_NAV', 'Postback log');
define('_POSTBACK_LOG', 'Postback link conversion log');
define('_COMPETITORS_INFO2', 'Your ads are highlighted in green');
define('_COMPETITORS_INFO', 'List of competitive ads with the same targeting as the ad');
define('_COMPETITORS', 'List of competitors');
define('_ALL_STAT_INFO', 'In parentheses indicate the number of auctions per day in affiliate networks');
define('_REGIONS_STAT_INFO', 'In parentheses are the number of auctions in the country per day in affiliate networks');
define('_REGIONS_FILTER_TOOLTIP', 'This filter has an advantage over the selected regions, if you select the same ones, then there will be no impressions');
define('_REGIONS_FILTER', 'Disallow regions');
define('_USER_ACTIVITY_TOOLTIP', 'User’s activity is determined by his interaction with ads, the more the user clicks on ads, the higher his activity and the higher the CTR of ads, and vice versa, if a user rarely or never clicks on ads, then his activity is low');
define('_USER_ACTIVITY_HIGH', 'high');
define('_USER_ACTIVITY_MIDDLE', 'average');
define('_USER_ACTIVITY_LOW', 'low');
define('_USER_ACTIVITY', 'User activity');
define('_PROMOCOD_ERR5', 'Your account is less than 7 days, to activate the promotional code you need to add funds');
define('_COUNTRYS', 'Countries');
define('_FORGET_TARGETS', 'Did not fill the fields');
define('_WM_STAT', 'Statistics');
define('_ADS_STAT', 'Ad statistics');
define('_ITDELETED', 'del');
define('_NOTACTIVE', 'off');
define('_ISACTIVE', 'on');
define('_FOR_GROUP', 'For group');
define('_GROUP_ERR', 'Enter group name');
define('_POPUP_ACTION', 'Do action');
define('_GROUP_ACTIONS', 'Group actions');
define('_GROUP_CHANGE_STATUS', 'Ad Group Status changed');
define('_ALL_OFF', 'Disable all');
define('_ALL_ON', 'Enable all');
define('_RENAME', 'Rename');
define('_GROUP_EMPTY', 'No group');
define('_GROUP_NAME', 'Group name');
define('_GROUP_ADD', 'Add group');
define('_GROUP', 'Group');
define('_FILTERS_IP_WARN2', 'IP is invalid');
define('_FILTERS_IP_WARN', 'IP range is invalid');
define('_FILTERS_IP_INFO', 'Deny separate ip: 1.1.1.1, subnet: 1.1, range: 1.1.1.1-2.2.2.2, each with a new line');
define('_FILTERS_IP', 'Deny IP');
define('_MORE_FILTERS', 'Additional filtering conditions');
define('_GUESTS', 'Accounts');
define('_ADVERT', 'Advertiser');
define('_WEBMASTER', 'Publisher');
define('_MACROS_DAYS', 'Subscription days');
define('_MACROS_BROWSER', 'Browser');
define('_MACROS_OS', 'Operating system');
define('_MACROS_MODEL', 'Mobile device model');
define('_MACROS_BRAND', 'Mobile device brand');
define('_MACROS_DEVICE', 'Device');
define('_MACROS_AD_DAYSPENT', 'Today ad spend');
define('_MACROS_AD_SPENTMONEY', 'Total ad spend');
define('_MACROS_AD_POSTBACK_MONEY', 'Amount transferred via postback');
define('_MACROS_AD_POSTBACK', 'The number of conversions transmitted through the Postback link');
define('_MACROS_AD_CLICKS', 'Ad clicks');
define('_MACROS_AD_VIEWS', 'Ad views');
define('_MACROS_AD_CATEGORY', 'Category ID');
define('_MACROS_AD_TEXT', 'Ad text');
define('_MACROS_AD_TITLE', 'Ad title');
define('_MACROS_AD_IMG', 'Ad img');
define('_MACROS_AD_ICON', 'Ad icon');
define('_MACROS_ISP', 'User Internet Service Provider');
define('_MACROS_CITY', 'User city');
define('_MACROS_REGION', 'User region');
define('_MACROS_COUNTRY', 'User country');
define('_MACROS_ISO', 'ISO country code');
define('_BALANCE_SLOW', 'Ads were slowed down because there were few funds on the balance.');
define('_CONVERSION_HOUR', 'By hours');
define('_SITES_TOOLTIP2', 'We recommend that you select sites only based on statistics. There are regular sites and landing pages in the system, landing pages can have a category that is indicated in square brackets, if several landing pages were used, then several categories will be indicated. In parentheses indicate the total number of subscribers.');
define('_SITESADD_INFO', 'Now you can select the code from the link Get the code and install it on the site. If you have difficulty installing the code, contact support.');
define('_CPVVIEWS_TOOLTIP', 'Pay-per-view impressions');
define('_SENDED_TOOLTIP', 'How many times an ad has been sent to subscribers');
define('_OPTIONS_CPC_TOOLTIP', 'When sending, clicks on notifications will be paid');
define('_OPTIONS_CPC', 'Allow pay per click for my subscribers');
define('_CHECK_SUBS_TOOLTIP', 'Data on average for 7 days');
define('_MYSUBS_ERR', 'Choose at least one ad sending method');
define('_PAY_TYPE_TOOLTIP', 'If you want to send the ad to the entire base of subscribers, then specify the form of payment');
define('_PAY_TYPE', 'Paid placing');
define('_SEND_MY_SUBS_TOOLTIP', 'Send ad to my subscribers database for free');
define('_SEND_MY_SUBS', 'By my subscribers');
define('_PROMOCOD_OK', 'The promotional code has been successfully activated! Your bonus balance is credited');
define('_PROMOCOD_SUMMA', 'Promotional code amount');
define('_PROMOCOD_ERR4', 'You can only activate one promotional code per day');
define('_PROMOCOD_ERR3', 'To activate the promotional code, you need to replenish the balance');
define('_PROMOCOD_ERR2', 'The promotional code has already been activated.');
define('_PROMOCOD_ERR1', 'No promotion code found');
define('_PROMOCOD_INFO', 'If you have a promotional code, then activate it through this form. Promotion code activation conditions:<br>1.only one promotional code per day <br>2. the second promotional code and further can be activated only if there are replenishment of the balance for the current day<br>3. if your account is less than 7 days, then to activate you need to replenish the balance of <br> 4. no more than 5 promotional codes per month');
define('_PROMOCOD_ACTIVE', 'Redeem promotional code');
define('_PROMOCOD', 'Promotional code');
define('_AVAIL_BALANCE', 'Available for withdrawal');
define('_BONUSES_TOOLTIP', 'Bonuses cannot be withdrawn, they can only be spent in the system.');
define('_BONUSES', 'Bonus funds');
define('_COLUMS', 'Colums');
define('_PROC', 'Percent');
define('_REF_DAYSTAT', 'Daily accruals');
define('_REF_PROC', 'Ref percents');
define('_REF_LINK', 'Your ref link');
define('_REF_INFO', 'Invite users by your ref link and get a percentage of their earnings. Ref percentage depends on the number of active users, from 5% to 10% of daily income. The percentage of income is calculated at the beginning of the next day for the previous one.');
define('_ALL_REFS', 'Total Referrals');
define('_NOTWORKS_TOOLTIP', 'User activity status, inactive - means that the account was blocked, or there was no expense on the account for yesterday.');
define('_NOTWORKS', 'inactive');
define('_WORKS', 'works');
define('_REFERALS', 'Referrals');
define('_URL_WRONG', 'Incorrect URL');
define('_PRICE_CHANGE', 'Price change');
define('_AUTO_MONEY_INFO', 'If you have not specified wallets before, then first specify the wallets and activate this option, then a select will appear to select the method of automatic payments and you need to save the settings again.');
define('_AUTO_MONEY_CHANGE', 'Payment method changed');
define('_AUTO_MONEY_OFF', 'Automatic Payments OFF');
define('_AUTO_MONEY_ON', 'Automatic Payments ON');
define('_AUTO_MONEY_SCORE', 'To the account');
define('_AUTO_MONEY', 'Automatic payouts');
define('_FILTERS', 'Filters');
define('_CONVERSION_LAYER1', 'Layer');
define('_CONVERSION_LANDING1', 'Landing');
define('_CONVERSION_CPANAME1', 'Affiliate Network');
define('_CONVERSION_OFFER1', 'Offer');
define('_CONVERSION_PROC', 'Percentage of earnings from all');
define('_CONVERSION_LAYER', 'By layers');
define('_CONVERSION_LANDING', 'By Landings');
define('_CONVERSION_OFFER', 'By offers');
define('_CONVERSION_CPANAME', 'Affiliate Networks');
define('_CONVERSION_INFO', 'Conversions passed through a Postback link, divided by targets. You can get the link on the ads page.');
define('_CONVERSION', 'Conversions');
define('_EPC', 'Average earnings per click');
define('_BYLANDS_TITLE', 'Landing subscription statistics');
define('_BYLANDS', 'By landings');
define('_OPERATION_ERROR', 'An error occurred while recording, we have already received a notification and are dealing with this issue.');
define('_WAYBLOCK_006', 'wrong category');
define('_RECOMAIND_BALANCE', 'If there is less than SUM on the balance, then the distribution of the balance during the day is automatically activated to slow down spending money.');
define('_ADD_ADS', 'Add ads');
define('_EDITING_ADS', 'Editing an Ad');
define('_DOUBLE_ADS', 'Copy ad');
define('_CPC_TRAF_FILTER', 'Refine volumes');
define('_CPC_TRAF_NAV', 'CPC volumes');
define('_CPC_TRAF_INFO', 'On this page, the available traffic volumes in partner networks are displayed on average per day, divided by target..');
define('_CPC_TRAF', 'Traffic volumes in CPC partner networks');
define('_MACROS_CLICKID', 'unique click id');
define('_MACROS_BID', 'Price per click (CPC only)');
define('_MONEYAPPROVED', 'Payment approved');
define('_POSTBACK_INFO', 'This link can be used to send conversion information  (POST & GET), replace {sub1} with the ad ID, {sub2} with the site ID, {sub3}  with the click ID. To get these parameters, use the appropriate macros for the link.<br>Replace also: {money} - for the amount of earnings, usd - currency code in ISO 4217 (http://en.wikipedia.org/wiki/ISO_4217), {status} - lead status, variants: \'approve\', \'approved\', \'confirm\', \'success\', \'ok\', declined: \'decline\', \'declined\', \'D\', \'F\', \'trash\', \'fail\'<br> Additional parameters: <br> {cpaname} - the name of the cpa network <br> {offer} - id or the name of the offer <br> {landing} - id or the name of the landing <br> {layer} - id or the name of the layer');
define('_POSTBACK', 'Postback link');
define('_CHOSE_REGIONS', 'choose country');
define('_REGION_DAY_PRICE', 'Daily prices for the region');
define('_USER', 'User');
define('_SMALL_DELETED', 'deleted');
define('_SMALL_UPDATED', 'updated');
define('_SMALL_ADDED', 'added');
define('_ADS_DELETED', 'Ads deleted');
define('_ADS_UPDATED', 'Ads updated');
define('_ADS_ADDED', 'Ads added');
define('_NEWURL_UPD', 'Link changed for ads');
define('_NEWURL_PLH', 'Specify a new address for selected ads');
define('_NEWURL', 'New URL');
define('_URLCHANGE', 'New URL');
define('_DAY24', 'allocate the budget throughout the day');
define('_NO', 'No');
define('_YES', 'Yes');
define('_REPEATS', 'Replays');
define('_ALLREQUEST_TOOLTIP', 'Displays the number of requests for advertising (not showing) on your chosen target for 2 days');
define('_ALLREQUEST', 'Total requests for selected targets in 2 days');
define('_SECTION', 'Section');
define('_MAILSTATUS2', 'Receive promo email');
define('_MAILSTATUS', 'Receive important email');
define('_NOMAIL', 'You have unsubscribed from receiving email');
define('_VIEWS_AUCTIONS', 'The percentage of views from auctions');
define('_MACROS_SUBID', 'site subid');
define('_MACROS_SITEID', 'site id');
define('_TOTALMONEYIS', 'Current expense');
define('_CATEGORY2', 'category');
define('_VIEWSPROCFROMALL', 'Percentage of views from all');
define('_SITESBLOCKED', 'Selected sites and subid added to blacklist.');
define('_BLOCKEDERR', 'Subid invalid');
define('_BLOCKEDINFO3', 'Here you can specify sites and subid to prevent your ads from displaying on them. Keep in mind that after you start sending out your advertising and blocking the site, it will take some time before the clicks stop coming.');
define('_BLOCKEDINFO2', 'Writes as site:subid (ID:SUBID), each with a new line');
define('_BLOCKEDINFO1', 'Specifies the site ID, each with a new line');
define('_BLOCKEDUPDATED', 'Lists updated');
define('_BLOCKEDSUBIDS', 'Blocked Subid');
define('_BLOCKEDSITES', 'Blocked sites');
define('_ONLYSITES', 'Display sites only');
define('_SITES_LIST', 'Site Lists');
define('_SITES_TOOLTIP', 'The network can have sub-sources that you can block separately.');
define('_SITES_SPENT', 'Spent by sites');
define('_MYADSITES', 'Site / Subid');
define('_VIEWS_PROC', 'views');
define('_REGIONS_SPENT', 'Spent by region');
define('_CPM_TITLE', 'Average cost of 1000 ad impressions');
define('_CPC_TITLE', 'Costs for Pay-Per-Click Ads');
define('_CPV_TITLE', 'Costs for ad pay-per-impression');
define('_SENDED_TITLE', 'Sending advertising, only with local placement');
define('_CR_TITLE', 'Conversion from sending to views, only with local placement');
define('_ADVERTISING', 'Advertising');
define('_BUDJETPAUSE', 'Stopped');
define('_SPENTTODAY', 'Spent today.');
define('_AUCTIONS_PROC', 'The percentage of impressions received from auctions, a low percentage means an insufficient price to win the auction.');
define('_AUCTIONS_INFO', 'Auctions are the number of hits in the top list of ads. The higher the cpc and balance, the higher the% of impressions received.');
define('_AUCTIONS', 'Auctions');
define('_BUDJET_ERROR2', 'Minimum daily budget');
define('_BUDJET_ERROR1', 'Minimum total budjet');
define('_CPCPRICE_ERROR2', 'Maximum cost per click');
define('_CPCPRICE_ERROR1', 'Minimum cost per click');
define('_CPCPRICE', 'CPC');
define('_TOTAL_BUDJET', 'Total budget');
define('_DAY_BUDJET', 'Daily budget');
define('_ADSTYPE_PARTNERS_INFO', 'sending to partner databases, less targeting conditions, pay per click, the ability to select specific networks in the list of sites');
define('_ADSTYPE_LOCAL_INFO', 'sending to a local subscriber base, more targeting conditions, payd per impressions, or free to your subscribers');
define('_ADSTYPE_PARTNERS', 'partner networks');
define('_ADSTYPE_LOCAL', 'local');
define('_ADSTYPEIS', 'Placement type');
define('_ADSTYPE', 'Choose placement type');
define('_CODETEXT27', 'Download and read the API connection rules for sending our advertising to your database.');
define('_CODETEXT26', 'To connect access you must first create an API key on the settings page. By API you get access to the list of pay-per-click ads, carefully read the rules for connecting api to the sending list in the attached documentation below, you also need to agree in advance on the conditions of connection and partner cooperation with support. If you have a large base, then we separately highlight it as VIP PARTNER. ');
define('_PARTNERURL', 'The address of the partner site cannot be changed');
define('_NOSELECTED', 'Nothing selected');
define('_ADVIMAGE', 'image');
define('_ADVICON', 'Icon');
define('_GENERATE', 'Create');
define('_LOAD', 'Download');
define('_LISTUPDATED2', 'Ads updated');
define('_BACKLIST', 'back to the list');
define('_EDITLIST', 'List editing');
define('_SAVE', 'Save');
define('_LISTDELETED', 'List deleted');
define('_LISTADDED', 'List added');
define('_LISTUPDATED', 'List updated');
define('_LISTNAMEWRONG', 'You must specify the name of the list');
define('_ADDLISTNEW', 'Add new');
define('_CHOSELIST', 'Select list');
define('_ADDLIST', 'Add to the list');
define('_COLADS', 'Ads');
define('_LIST', 'My listings');
define('_MYPUSH_PROMO', 'MyPushAdmin - individual push subscription management system');
define('_DAYSPRICE_REGION', 'Daily prices by region');
define('_DAYSPRICE', 'Daily prices');
define('_SELLPRICE_TOOLTIP', 'The average sale price of a subscription on the exchange for the selected conditions');
define('_SUBSAVGPRICE_TOOLTIP', 'The average purchase price of a subscription on the exchange for the selected conditions');
define('_SUBSAVGPRICE', 'Subscription price');
define('_PRICEWRONG', 'No selection condition specified');
define('_GETIT', 'Get');
define('_WHATPRICE', 'Check prices');
define('_LANG_BY', 'By languages');
define('_LANG1', 'Language');
define('_PRICES_INFO', 'Here are displayed the prices for traffic on the system, and obtained from the feeds of partner networks, divided into: <br> CPC - average price per click <br> CPM - average price of 1000 ad views <br>CPM send - average earnings from 1000 sendind');
define('_PRICES_TITLE', 'Prices');
define('_PRICES_IPRANGE', 'By IP range');
define('_PRICES', 'Traffic prices');
define('_NEEDMORETRAFFIC', 'Need more Push trafic?');
define('_CLICKPRICE_TITLE', 'Average cost per click');
define('_CREATIVEDOUBLE', 'Duplicate ads');
define('_COPYERROR', 'An error occurred while copying the file.');
define('_COPYINGADVINFO', 'You can replace any image.');
define('_COPYINGADV', 'Copy ad');
define('_LOADERROR', 'Error file upload');
define('_FILEFORTAMTS', 'Error. Permissible formats');
define('_MAXFILESIZE', 'Error. Maximum file size');
define('_SITETYPE', 'Choose the type of site');
define('_CREATIVMENU', 'Ad Base');
define('_NOTHINGFOUND', 'Nothing found');
define('_TEXTS', 'Texts');
define('_DAYS_LEFT', 'Days added');
define('_CTR_TOOLTIP', 'The percentage of clicks on ad from views');
define('_SHOWING_TOOLTIP', 'Number of announcements during the sending');
define('_DATEADD', 'Date added');
define('_SHOWING', 'Showing');
define('_DETAIL_TITLE', 'Information about ads');
define('_CHOSE3', 'Choose');
define('_DETAIL', 'More');
define('_CREATIV', 'Creatives');
define('_CREATIV_TITLE', 'Search for creatives');
define('_FEEDTEMPLE_PARAM1', 'Your value for');
define('_FEEDTEMPLE_TOOLTIP', 'You can choose a settings template for each network, all you have to do is to register your data from the feed, which you can get from the network support.');
define('_FEEDTEMPLE', 'Select settings');
define('_HOMETEXT', '<div align=center>Welcome!</div>Thank you for sign up! You can get started right now depending on your targets:<br>1. <strong>Do you want to make money</strong>, then go to Sites and add a site or landing page, put the code on the site or send users by link, start collecting subscriptions and make money on them.<br>2. <strong>You need traffic</strong>, then go to the Ads and add your ad, after filling in the fields, click Check to check the number of available subscribers for your conditions, if any, refill the balance at the link above, and specify the price for 1000 views of your ad, and then start sending, at the same time sending to subscribers free of charge.<br>Have a good job! If you have any questions, write to Telegram, which is listed on the left of the menu, either by email: support@3xpush.com, and connect our telegram bot to quickly receive system notifications');
define('_DOMAINFAIL2', 'Domain is invalid');
define('_USER_ADD_LAND', 'Landing created! Now go to the landing page settings to choose a template, or create your own');
define('_CODE', 'Code');
define('_PAGEURL2', 'Page address');
define('_CONTENT1', 'content');
define('_DATEPUB', 'Publication date.');
define('_CONTENT', 'Content');
define('_MAILCHECK', 'An email has been sent to your email, click on the link to confirm your email.');
define('_MAILAPPROVE', 'Confirm email');
define('_MAILNEEDAPROVE', 'To order the payment you need to confirm your email. Go to your account settings and send a confirmation request, then check your mail.');
define('_MAILAPPROVER', 'Email approved');
define('_IMGVIEWPROC', 'Percentage of views from sending');
define('_UNSUBSPROC', 'Percentage of sending lists');
define('_LOADIMG', 'Load picture');
define('_PRICEDISALED', 'You can change the price every 10 minutes.');
define('_STATUSDEL', 'Deleted');
define('_REPORTSTIME', 'Runtime');
define('_REPORTS1', 'System reports');
define('_REPORTS', 'Reports');
define('_NEXTSEND', 'Next send');
define('_LASTSEND', 'Last send');
define('_SEND_AFTERCLICK_TOOLTIP', 'How long after click on push to do the next send');
define('_SEND_AFTERVIEW_TOOLTIP', 'How long after watching push do the next send');
define('_SEND_FORNEW_TOOLTIP', 'How long after the subscription do the first send');
define('_OPTIONS_AFTERCLICK', 'After click send via');
define('_OPTIONS_AFTERVIEW', 'After viewing send via');
define('_OPTIONS_AFTERCREATE', 'After subscription send via');
define('_NOT', 'No');
define('_REDIRECTURL', 'URL after subscribe');
define('_LANDINGCHOSEN', 'Selected Landings');
define('_OPEN', 'Open');
define('_NSFAIL', 'DNS domain is configured incorrectly or not yet updated.');
define('_DOMAINSINFO', 'To bind the domain, add to the settings DNS:<br> <strong>ns1.3xpush.com</strong><br> <strong>ns2.3xpush.com</strong><br><br>As soon as ns are updated, an SSL certificate will be created for the domain for its proper operation.');
define('_LANDINGDEL', 'Landing deleted');
define('_LANDINGS1', 'Landings');
define('_LANDEDIT', 'Edit landing');
define('_LANDADDED', 'Landing added, activation required.');
define('_LANDUPDATED', 'Landing updated');
define('_PREVIEW', 'Preview');
define('_CREATELANDING', 'Create Landing');
define('_LANDINDSELECTED', 'You chose a ready landing page, settings from the editor are not used to activate the editor, cancel the landing page. Specify settings for landing below.');
define('_LANDINDEL', 'Landing canceled');
define('_LANDINGSET', 'Landing set');
define('_LANDINGSINFO', 'You can choose a ready landing page from the list, just click Select and then this template will be used for your landing page. If you want to use your template again, just click Cancel.');
define('_CRTOOLTIP', 'Conversion from views to subscribers');
define('_LANDINGS', 'Ready landings');
define('_DOMAINFORLINKS', 'Domain for links');
define('_DOMAINDELETED', 'Domain deleted');
define('_KEYDELETED', 'Api key deleted');
define('_DOMAINFAIL', 'Domain does not exist or configured incorrectly');
define('_DOMAINADDED', 'Domain added');
define('_DELDOMAIN', 'Delete domain');
define('_DOMAINS', 'Domains');
define('_DOMAIN', 'Domain');
define('_ADDDOMAIN', 'Add domain');
define('_NEWS1', 'news');
define('_NEWS', 'News');
define('_COMFIRMACTION', 'Confirm action');
define('_SORTS', 'Sort');
define('_ANSWER', 'Answer');
define('_QUESTION', 'Question');
define('_FAQ', 'Questions and answers');
define('_REGSTAT_CPM', 'Average earnings from 1000 sending');
define('_REGSTAT_CLICKPRICE', 'Average cost per click');
define('_REGSTAT_CTR', 'Percentage of views clicks');
define('_REGSTAT_UNS_PROC', 'Percentage of unsubscribe from all');
define('_REGSTAT_UNS', 'Unsubscribe');
define('_REGSTAT_SENDED_PROC', 'The percentage of sending from all');
define('_REGSTAT_EMPTY_PROC', 'The percentage of empty requests from all');
define('_REGSTAT_EMPTY', 'Number of requests without advertising for sending');
define('_REGSTAT_CR2', 'The percentage of subscriptions from all');
define('_REGSTAT_CR', 'Conversion from requests to subscriptions');
define('_REGSTAT_NEW', 'New Subscribers');
define('_REGSTAT_REQ', 'Subscription requests');
define('_MONEYADDED', 'Funds deposited');
define('_PAYMENTID', 'Payment number');
define('_ADMIN_ADD_FUNDS', 'Deposit funds');
define('_EXCHANGEADDTOOLTIP', 'You can create a rule for auto sales subscriptions at your prices with given conditions.');
define('_EXCHSELLERROR', 'An error occurred while adding subscribers to the exchange');
define('_SUMMOREBALANCE', 'Amount more balance');
define('_VIEWMYTOOLTIP', 'If you want to delete your application, select this condition.');
define('_DELBUYOK', 'Selected bids removed, deposit returned to balance');
define('_DELBUY', 'Do you want to delete selected purchase requisitions? Your balance will be returned');
define('_WAYBLOCK', 'Reason for blocking');
define('_WAYBLOCK_005', 'inappropriate content');
define('_WAYBLOCK_004', 'invalid images');
define('_WAYBLOCK_003', 'invalid content');
define('_WAYBLOCK_002', 'Malvari');
define('_WAYBLOCK_001', 'malicious link');
define('_RULES', 'Rules');
define('_PAYMETHOD', 'method of payment');
define('_WALLET', 'Wallet');
define('_COMISSION', 'Comission');
define('_DESCRIPTION', 'management service push subscriptions, advertising, earnings on shows, clicks and sales!');
define('_LINKDOMAIN', 'Landing Domain');
define('_CODEDOMAIN', 'Domain for codes');
define('_HOURSENDED', 'Sending by hour');
define('_HOURCLICKS', 'Clicks by hour');
define('_HOURSUBS', 'Subscriptions by the hour');
define('_MAXUSERSEND', 'Max. user sending');
define('_CANCEL2', 'Cancel');
define('_HIDE', 'Hide');
define('_TEXT2', 'text');
define('_SHOW', 'Show');
define('_MAILSCANCEL', 'Canceled');
define('_MAILSNOSENDED', 'Not sent');
define('_MAILSSENDED', 'Sent');
define('_MAILS', 'Mails');
define('_ALLADS', 'Ads');
define('_MODERATION', 'Moderation');
define('_MODERATEBLOCKED', 'Banned');
define('_MODERATESUCCES', 'Ad status changed');
define('_MODERATEBLOCK', 'Disallow');
define('_MODERATEALLOW', 'Allow');
define('_MODERATEYES', 'Verified');
define('_MODERATENO', 'Not verified');
define('_SUBDAYS', 'Filters subscribers by number of subscription days');
define('_AOPTIONS13', 'Website address');
define('_AOPTIONS12', 'Allow payment for impressions');
define('_AOPTIONS11', 'Email response');
define('_AOPTIONS10', 'Email support');
define('_AOPTIONS9', 'Project name');
define('_COMMON', 'Common');
define('_AOPTIONS8', 'Percentage of cost per impression');
define('_AOPTIONS7', 'Max. price per 1000 impressions');
define('_AOPTIONS6', 'Min price per 1000 impressions');
define('_AOPTIONS5', 'Min payout amount');
define('_AOPTIONS4', 'Max. subscriber price');
define('_AOPTIONS3', 'Min subscriber price');
define('_AOPTIONS2', 'Percentage of subscriber sale');
define('_AOPTIONS1', 'Min top up amount');
define('_ONLYMY', 'only mine');
define('_CHECKSUMWRONG', 'Amount check failed, possibly hacking');
define('_WITHDROWALBACK', 'Payments canceled, funds returned to balance');
define('_WITHDROWALDONE', 'Payments are made');
define('_PUSHBUTTON', 'Button text');
define('_CANNOT_CHANGE_SCORE', 'You cannot change wallets while you have requests for payment.');
define('_ACHECKCODE_ERROR', 'Verification code is incorrect, check the system for hacking!');
define('_ASCOREERROR', 'This wallet is not in the user settings');
define('_USERBLOCKED', 'User is blocked');
define('_DELETEPAY', 'CANCEL PAY');
define('_DONEPAY', 'PAID');
define('_MASSPAYMENT', 'Start mass payments webmoney');
define('_LOADLIST', 'load list');
define('_WITHDROWALS', 'Withdrawals');
define('_ALLOPERATIONS', 'All operations');
define('_PAYMENTSTATUS3', 'calceled');
define('_SENDEDBYUSER2', 'Sending per user');
define('_ONPAGE', 'on page');
define('_PAGE', 'Page');
define('_ADMIN_SHOW_ALL', 'show all');
define('_ADMIN_FILTERS', 'Admin filters');
define('_CPVVIEWSTITLE', 'Paid views for all subscribers');
define('_CPVVIEWS', 'Paid views');
define('_CPVPRICE', 'Price per 1000 ad impressions');
define('_CPVPAYINFO', 'send all the system subscribers with pay per impression');
define('_CPVPAY', 'Pay for impressions');
define('_LOCALTIME_TOOLTIP', 'Your time zone for correct time display');
define('_STATPERIOD_TOOLTIP', 'Number of days for default statistics');
define('_MYADSPRIORITY_TOOLTIP', 'Select the priority of your ads over others to sending.');
define('_MAXUNSUBSPROC_TOOLTIP', 'Maximum percentage of unsubscribes to block ads');
define('_PUSHUNSUBS_TOOLTIP', 'If allowed, ads with a percentage of unsubscribing more than the specified below will be prohibited from being sent.');
define('_STOPWORDS_TOOLTIP', 'Specify the words, in the presence of which in the ad it will be rejected for sending');
define('_MINSTAVKA_TOOLTIP', 'Minimum cost per click from feeds');
define('_PUSHLIFE_TOOLTIP', 'The time during which the user must receive a notification, if the time has passed, the user will no longer receive it');
define('_BIGIMG_TOOLTIP', 'You can disable the sending of a large image that is displayed only in the Chrome browser');
define('_CHECKURL_TOOLTIP', 'Checking the availability of external links from feeds and your ads, if the link is not available, for example, the site is down, then the feed or ad will be automatically disabled');
define('_AFTERCLICK_TOOLTIP', 'If the user has already made a click on the ad, then you can no longer send it');
define('_MAXSEND_ADV_TOOLTIP', 'The limit on sending new ads, if after a specified number of sending, there were no clicks, then it goes down in the list');
define('_MAXSEND_TOOLTIP', 'How many in general send one advertisement to user');
define('_USER_MESAGES_TOOLTIP', 'Periodicity of sending the 1st ad to the user in the specified period.');
define('_SEND_EVERY_TOOLTIP', 'Specify the frequency of sending push, the more often, the more income, but the faster users will unsubscribe');
define('_CPVALLOW_TOOLTIP', 'Other users will be able to send their advertisements to your database with payment for impressions on the auction, who will offer more will get the push.');
define('_CPVALLOW', 'Allow sending on my base pay-per-impression');
define('_SUBSTOTALTOOLTIP', 'Users owners other subscribers who allowed sending on their base with pay per impression.');
define('_SUBSTOTAL', 'Total system');
define('_STATUSUPDATE', 'User status changed');
define('_EMAILNOTAPPROVE', 'Not confirmed');
define('_ACCCREATED', 'Account created');
define('_LASTLOGIN2', 'Last sign in');
define('_ACTIVATE', 'Activate');
define('_BLOCK', 'Block');
define('_USERS', 'Users');
define('_NOLINK_EMPTY', 'Check the box if you want to pass the parameter from the field, not by reference');
define('_LINKS_INFO', 'Parameters in the link: <strong>subid</strong> - you can specify any parameter to collect statistics., <strong>tag</strong> - to divide subscribers into categories, <strong>price</strong> - click cost, for profit calculation');
define('_REGIONS_TOOLTIP', 'Enter the ISO country codes separated by commas for which to connect this feed.');
define('_BIDCOEF_TOOLTIP', 'If the network counts on all clicks, then you can lower their BID by a specified percentage to eliminate the discrepancy in income.');
define('_RATE_TOOLTIP', 'If the feed currency is not in USD, then indicate the rate in relation to USD, if it is greater, then just a number, if less / number (division sign and number)');
define('_ACCOUNTUPDATE', 'Account information updated');
define('_LOGIN_EMPTY', 'Specify login');
define('_MAIL_EMPTY', 'Specify email');
define('_POSTBACKINFO', 'The request will be sent by the POST method, the names of the parameters correspond to the name of the macros in upper case.');
define('_REFERERMACROS', 'Subscription source page');
define('_POSTBACKTOOLTIP', 'In this field you can specify the link to which the notification will come when the user subscribes. You can use macros.');
define('_TIMETOOLTIP', 'Choose which time to take into account for the sending condition, current server, or local user. To work in the settings set your time zone.');
define('_SITESTOOLTIP', 'Choose how you plan to get subscriptions, if through arbitration and buying traffic by reference, select Landing.');
define('_MINEFFECTTOOLTIP', 'Here you can specify the minimum percentage of the activity of the subscribers of the seller, which consists of the index of views and clicks on push');
define('_MINEFFECT', 'Min seller subscribers activity');
define('_QUANTITYTOOLTIP', 'The remainder of the total');
define('_YOUBLOCKED', 'Not all requests are shown, as some buyers have blocked you. Pay attention to your subscriptions, possibly because of their low quality..');
define('_TOOLTIPEFFECTSUBS', 'The effectiveness of subscribers is the sum of the number of pushes, ad views and clicks on them, the lower it is, the less quality subscriptions');
define('_SUBSSOURCESLANDING', 'Landing, arbitration');
define('_SUBSSOURCES', 'Sources of subscriptions');
define('_SUBSACTIVITY', 'Subscription activity');
define('_YOUBUYED', 'You bought');
define('_ACTIVESUBS', 'Active Subscribers');
define('_ALLSUBS', 'Total Subscribers');
define('_ALLSELL2', 'Was sold');
define('_ALLSELL', 'Total for sale');
define('_SELLERINFO', 'Seller Information');
define('_BLADDED', 'Selected sellers have been blacklisted');
define('_BLADD', 'Add in BL');
define('_BLDELETED', 'Seller removed from blacklist');
define('_SHOW', 'Show');
define('_BLSELLER', 'Shown excluding blocked sellers');
define('_AUTOSELLEDIT', 'Edit rule');
define('_AUTOSELLDEL', 'Delete rule');
define('_AUTOSELLSTATUS', 'Rule status changed');
define('_AUTOSELLADDED', 'Rule successfully added');
define('_AUTOSELLIMPORTANT', 'Specify at least one condition in the drop-down lists to create a rule');
define('_AUTOSELLRULES', 'The automatic sale rule works only for new subscribers, immediately at the time of the subscription, if the subscriber falls under the specified conditions, then it is added to the exchange.');
define('_EXCHANGEADD2', 'Add auto selling rule');
define('_EXCHANGEADD', 'Add rule');
define('_EXCHANGEAUTO', 'Auto selling rules');
define('_OPERATIONSELL2', 'buy');
define('_OPERATIONSELL', 'sale');
define('_MYDEALS', 'My deals');
define('_ISCHECKOUT', 'withdrawal');
define('_CHECKOUTSUCCESS', 'Withdrawal request successfully created');
define('_CHECKOUTERR3', 'Error when ordering withdrawal');
define('_CHECKOUTERR2', 'Invalid amount');
define('_CHECKOUTERR', 'Amount more balance');
define('_CHECKOUTTYPE', 'Payment method');
define('_CHECKOUTSUM', 'Specify the amount to pay');
define('_CHECKOUNOSCORE', 'Specify wallets for payments on the Settings - Finance page');
define('_CHECKOUTRULES2', 'All ordered payments are processed once a week on Mondays. In parentheses are the commission for withdrawal.');
define('_CHECKOUTWRONG', 'Not enough funds on balance for withdrawal');
define('_CHECKOUTRULES', 'Minimum amount to pay');
define('_CHECKOUT', 'Withdrawal of funds');
define('_PASSCHANGE', 'The account password has been changed, if you did not do it, then immediately report to support. User details:');
define('_ACCOUNTUPDATEMAIL', 'Changed account settings');
define('_NEWMAIL', 'In the account settings email has been changed, click on the link to confirm mail');
define('_SCOREUPDATEEMAIL', 'Your wallets have been updated in your account');
define('_SCOREUPDATE', 'Wallets have been updated');
define('_FINANCE', 'Finance');
define('_OPERATION', 'Operation');
define('_PAYFAIL', 'An error occurred while paying a payment.');
define('_PAYSUCCESS', 'Payment successfully credited!');
define('_THROW', 'through');
define('_PAYADD', 'Top up balance on');
define('_MINSUMMAERR', 'Minimum recharge amount');
define('_PAYTHROW', 'Recharge through');
define('_MINSUMMARULE', 'Minimum recharge amount');
define('_PAYHISTORY', 'Payout history');
define('_PERIOD', 'Period');
define('_OSTATOK', 'residue');
define('_PAYMENTSTATUS2', 'wait');
define('_PAYMENTSTATUS', 'paid');
define('_PAYMENTTYPE2', 'write-off');
define('_PAYMENTTYPE1', 'recharge');
define('_PAYMENTTYPE', 'Payment method');
define('_BALANCE', 'Balance');
define('_BUYIMPORTANT', 'Specify at least one condition in the drop-down lists for creating an request');
define('_SIDERROR', 'No site for linking subscribers');
define('_NEWBUYSUCCESS', 'Purchase request successfully created! You can track completed transactions on the My deals page.');
define('_NOMONEY2', 'Insufficient amount on balance for deposit! <a href=?m=balance&sum=SUM>Top up balance on SUM$</a>');
define('_RULESWRONG', 'Conditions are incorrect, check the form again.');
define('_DEPOSITINFO', 'The specified amount will be deducted from your balance in the deposit for the purchase');
define('_NEWBUY2', 'Apply for the purchase of subscribers');
define('_NEWBUY', 'New buy');
define('_DELSUCCESS', 'Records deleted successfully');
define('_DELCONFIRM', 'Confirm the deletion of selected subscribers from the sale');
define('_ERROPERATION', 'An error occurred while performing the operation.');
define('_EXCHANGEDEL', 'Remove from sale');
define('_SELLINFO2', 'subscribers successfully put up for sale');
define('_SELLINFO', 'Subscriber put up for sale');
define('_NOSELL2', 'You can not re-set subscriptions for sale');
define('_MAXPRICEERR', 'Price above maximum');
define('_MINPRICEERR', 'Price below minimum');
define('_SELLSUBS3', 'Confirm action to add selected subscribers to the exchange.');
define('_SELLSUBS4', 'For subscribers on the exchange, push is not sending!');
define('_ALLSUMMA2', 'Total amount');
define('_PRICEPERSUB', 'Price per subscriber');
define('_GOSELLSUBS', 'Put up for sale');
define('_NOSELL', 'Selected subscribers are not available for sale.');
define('_IPRANGE', 'IP range');
define('_IPRANGES', 'IP ranges');
define('_WITHCOMISSION', 'Minus the commission, you will receive');
define('_SALESWRONG', 'You do not have suitable terms of subscribers, or the conditions of purchase have changed, refresh the page');
define('_SALES', 'Sold subscribers');
define('_ADDNEWSITE', 'Add site / landing page to buy subscriptions');
define('_CHOSENEWSITE', 'Choose which site to link subscribers to.');
define('_PUSHSELLWARN', 'This operation will not be canceled later.');
define('_PUSHSELL', 'Confirm the transaction to sell your subscribers for the specified amount.');
define('_ALLSELLSUBS', 'Total matching subscriptions');
define('_EXCHNOSUBS', 'You have no suitable subscribers for the terms of sale');
define('_SELLSUBS', 'Sell subscribers');
define('_SELL', 'Sell');
define('_SUMMA', 'Amount');
define('_DATESFROM', 'Subscription days from');
define('_DATESTO', 'Subscription days to');
define('_PER', 'for');
define('_QUANTITY', 'Qty');
define('_CONDITION', 'Conditions');
define('_EXCHTITLE1', 'Selling');
define('_EXCHTITLE2', 'Buying');
define('_FINISHBUY', 'Subscriptions successfully purchased and transferred to your account. The list of your subscribers in the Webmaster - Statistics section - <a href=?m=subscribers>Subscribers</a>');
define('_ALLREADYBUY', 'Selected subscriptions have already been purchased.');
define('_NOMONEY', 'Insufficient account balance for payment! <a href=?m=balance&sum=SUM>Top up balance on SUM$</a>');
define('_ONYOURBALANCE', 'On your balance');
define('_ALLSUMMA', 'To the amount of');
define('_CHECKED', 'Chosen');
define('_EXCANGEERROR', 'An error occurred while selecting subscribers.');
define('_BUYSUBS', 'Buy subscribers');
define('_SHOWMY', 'output my proposal');
define('_CHOSENALL', 'Chose all');
define('_CHOSEN', 'Chosen');
define('_TAGS', 'Tags');
define('_MODELS', 'Device models');
define('_BRANDS', 'Brands');
define('_SUBSDATE2', 'Subscription days');
define('_CITYS', 'Citys');
define('_CHOSE2', 'Choose');
define('_BUY', 'Buy');
define('_DAYSSHORT', 'days');
define('_SUBSDATE', 'Subscription time');
define('_PRICE', 'Price');
define('_SELLER', 'Seller');
define('_EXCHANGE2', 'Subscribers exchange');
define('_EXCHANGE', 'Exchange');
define('_PASSWRONG', 'Password must be from 6 characters');
define('_PASSRULES', 'From 6 to 20 characters');
define('_MAILWRONG', 'Email is incorrect');
define('_NAMEWRONG', 'Name is incorrect');
define('_LOGINWRONG', 'Login is incorrect');
define('_LOGINRULES', 'Only letters and numbers. From 4 to 20 characters');
define('_NEWUSERTEXT', 'Congratulations on your successful registrar on 3xpush!<br><br>Your login: [login]<br>Password: [pass]<br><br>Sign in - <a href=[url]>[url]</a>');
define('_NEWUSER', '3xpush - Successful registration');
define('_CAPTCHAERROR', 'Captcha check failed');
define('_REGISTEROK', 'Congratulations on your successful registration, you can now log in!');
define('_ISLOGIN', 'Username is already in use, select another');
define('_REGISTER', 'Sign up');
define('_HELLO', 'Hello');
define('_ADDTOKEN', 'Add key');
define('_EDITTOKEN', 'Edit key');
define('_DELTOKEN', 'Delete key');
define('_TOKEN', 'Key');
define('_USERNAME', 'Name');
define('_NODATA', 'No data');
define('_HIDEIMG', 'Hide image');
define('_NEWPASSWRONG', 'Passwords do not match');
define('_NEWPASS', 'New password');
define('_REPEAT', 'Repeat');
define('_SENDOPTIONS', 'Send options');
define('_ACCOUNT', 'Account');
define('_ACCOUNTOPTIONS', 'Account options');
define('_UNSUBSCRIBED', 'Unsubscribed');
define('_BYBROWSER', 'By browsers');
define('_BLOCKEDPROC', 'Percentage of rejected requests');
define('_CRTITLE', 'Conversion from requests to subscriptions');
define('_CLICKPRICETITLE', 'Average cost per click');
define('_SENDBYUSERTITLE', 'Subscriptions to subscriber');
define('_VIEWSPROC', 'The percentage of views push on mailings');
define('_REQUESTPROC', 'Percentage of subscription requests from landing page openings');
define('_PROFIT', 'Profit');
define('_MONEYSPENTTITLE', 'Spent on traffic');
define('_MONEYSPENT', 'Spend');
define('_LANDVIEWS', 'Open landing');
define('_IFRUPDATE', 'Iframe/Redirect updated');
define('_REDIRTYPE3', 'confirm age (18+)');
define('_REDIRTYPE2', 'load file');
define('_REDIRTYPE1', 'watch video');
define('_REDIRTYPE0', 'follow the link');
define('_DEFAULT', 'By default');
define('_IFRAMEOPTIONS2', 'Don`t redirect to subdomain after failure');
define('_IFRAMEOPTIONS1', 'Subscriptions to open the site');
define('_LANDOPTIONS7', 'To work you should specify links &nbsp;<b class=red>class="redirect-link"</b>, or enclose a block of links to &nbsp;<b class=red>&lt;div id="push_links"&gt;...&lt;/div&gt;</b> so that all links in the block are redirected.');
define('_LANDOPTIONS6', 'template type');
define('_LANDOPTIONS5', 'Resubscriptions for click-throughs');
define('_LANDOPTIONS4', 'Text in the overlapping block');
define('_LANDOPTIONS3', 'Display X, to close the block');
define('_LANDOPTIONS2', 'To block page');
define('_LANDOPTIONS1', 'Display subscription via');
define('_INCLUDESCRIPTS', 'Connect codes');
define('_HOURSSEND', 'subscription hours');
define('_HOURS2', 'Hours');
define('_DAYS2', 'Days');
define('_DAYSSEND', 'Sending days');
define('_LOCALTIME', 'Local time');
define('_USERTIME', 'Users` time');
define('_DOUBLEFIELD', 'Record doubled');
define('_CHOSETAGS', 'Сhoose tags');
define('_CHOSEDEVICES', 'Сhoose devices');
define('_CHOSEDEVTYPES', 'Сhoose device type');
define('_CHOSELANGS', 'Сhoose languages');
define('_CHOSESUBID', 'Сhoose subid');
define('_CHOSESITES', 'Сhoose sites');
define('_CHOSEREGION', 'Сhoose region');
define('_ALLFOUND', 'Total records');
define('_BIDCOEF', 'Bid correction');
define('_BYSUBID', 'By subid');
define('_OTHER', 'Other');
define('_COPYLANDNO', 'An error occurred while copying the page');
define('_COPYLANDOK', 'The page copied successfully');
define('_DOUBLE', 'Copy');
define('_NOADV', 'no ads');
define('_ISCAT', 'This category already exists');
define('_OR', 'or');
define('_INSTALL1', 'Сhoose language');
define('_INSTALL2', 'More');
define('_INSTALL3', 'Checking the required components');
define('_INSTALL4', 'To continue the installation, you must install all the components');
define('_INSTALL5', 'Mysql and Memcache Settings');
define('_INSTALL6', 'Server');
define('_INSTALL7', 'Login');
define('_INSTALL8', 'Password');
define('_INSTALL9', 'Database');
define('_INSTALL11', 'Invalid connection data, please go back and try again.');
define('_INSTALL12', 'Back');
define('_INSTALL13', 'Connection installed successfully!');
define('_INSTALL14', 'Memcache server');
define('_INSTALL15', 'Project folder');
define('_INSTALL16', 'Project settings');
define('_INSTALL17', 'Database flowing');
define('_INSTALL18', 'Database installed successfully!');
define('_INSTALL19', 'An error occured while installing the database, try again, or flow the database manually through phpmyadmin');
define('_INSTALL20', 'Site domain');
define('_INSTALL21', 'Fill in all the fields');
define('_INSTALL22', 'Congratulations! Settings have been completed.');
define('_INSTALL23', 'Error reading the file, check that all files are in place');
define('_INSTALL24', 'Error writing the file, check that the write permissions are set correctly');
define('_INSTALL25', 'Registration key');
define('_NOACCESS', 'No access rights');
define('_LINES', 'Display');
define('_MESSAGES', 'System messages');
define('_NEWALERTS', 'You have X new alerts');
define('_LANDUPDATE', 'Landing updated');
define('_LANDUPDATENO', 'Landing is not updated');
define('_LANDOPTION', 'Landing settings');
define('_LANDHTML', 'Set HTML');
define('_MYADV2', 'My ads');
define('_DECLINED', 'Declined');
define('_ACTIONS', 'Actions');
define('_MYADSTAT', 'My ads statistics');
define('_ADDADMIN', 'Add user');
define('_DELETEADMIN', 'Delete admin');
define('_EDITADMIN', 'Edit admin');
define('_BLOCKED', 'Blocked');
define('_LOGIN', 'Login');
define('_PASS', 'Password');
define('_ENTER', 'Sign in');
define('_EMAIL', 'Email');
define('_REMEMBERME', 'Remember me');
define('_LASTLOGIN', 'Last login');
define('_LASTACTIVE', 'Last activity');
define('_ROLE', 'Role');
define('_ADMINS', 'Users');
define('_LOGOUT', 'Logout');
define('_LOGIN1', 'Error in access data or admin is blocked.');
define('_HOMETEXT1', 'Week statistics');
define('_HOMETEXT2', 'Top sites by subscriptions');
define('_HOMETEXT3', 'Last subscriptions');
define('_HOMETEXT4', 'Top regions by subscriptions');
define('_HOMETEXT5', 'Subscriptions by device type');
define('_HOMETEXT6', 'Subscriptions by OS');
define('_HOMETEXT7', 'Last sending');
define('_HOMETEXT8', 'Last clicks');
define('_HOMETEXT9', 'Total earnings');
define('_HOMETEXT10', 'Total sending');
define('_HOMETEXT11', 'Total clicks');
define('_PUSHUSER', 'User');
define('_DELADV', 'Delete ad');
define('_CHECK', 'Check');
define('_CHANGESTATUS', 'Status changed');
define('_ICON192', '192x192 Icon');
define('_ICON360', '360x240 Image');
define('_MACROS', 'Macros');
define('_MACROS1', 'to put site number');
define('_MACROS2', 'subscribers` ip');
define('_MACROS3', 'subscribers` token');
define('_MACROS4', 'subid setting');
define('_MACROS5', 'subscribers` language');
define('_MACROS6', 'device');
define('_MACROS7', 'device brand');
define('_MACROS8', 'device model');
define('_MACROS9', 'subscription page');
define('_MACROS10', 'unique user hash ID');
define('_MACROS11', 'subscription time');
define('_MACROS12', 'browser');
define('_MOBDEV', 'Mobile device brand');
define('_MODEL2', 'Device model');
define('_CITY', 'City');
define('_CITY2', 'City on ru');
define('_COUNTRY', 'Subscribers` country');
define('_COUNTRY2', 'Country on ru');
define('_CHOSE', 'choose');
define('_TEXT', 'Text');
define('_VIEWS', 'Views');
define('_MAXSEND', 'Max sending');
define('_LANGS', 'Languages');
define('_DEVICES', 'Devices');
define('_DEVICE', 'Device');
define('_DEVTYPES', 'Devices type');
define('_BROWSERS', 'Browsers');
define('_CATEGORY', 'Category');
define('_ON', 'On');
define('_OFF', 'Off');
define('_TARGET', 'Targeting');
define('_MYADV', 'Ads');
define('_MYADV1', 'Management');
define('_MYADV3', 'ads');
define('_MYADV4', 'Insert title');
define('_MYADV5', 'Insert description');
define('_MYADV6', 'Image not loaded');
define('_MYADV7', 'Choose at least one hour');
define('_MYADV8', 'Choose at least one day');
define('_OPTIONS1', 'Enable sending');
define('_OPTIONS2', 'Sending every');
define('_OPTIONS3', 'Send 1 ad to user');
define('_OPTIONS4', 'Maximum send ad to user');
define('_OPTIONS5', 'Maximum number of sending without a click');
define('_OPTIONS6', 'Don`t send again after click');
define('_OPTIONS7', 'Break up the e-mailing list by');
define('_OPTIONS8', 'Cut title');
define('_OPTIONS9', 'Cut description');
define('_OPTIONS10', 'Domain for push');
define('_OPTIONS11', 'Minimal bid');
define('_OPTIONS12', 'Test push');
define('_OPTIONS13', 'Test uid');
define('_OPTIONS14', 'Stop words');
define('_OPTIONS15', 'Enable block by unsubscriptions');
define('_OPTIONS16', 'Max percentage of unsubscriptions for the block');
define('_OPTIONS17', 'Sorting ads');
define('_OPTIONS18', 'once in a');
define('_OPTIONS19', 'times');
define('_OPTIONS20', 'pcs');
define('_OPTIONS21', 'symb');
define('_OPTIONS22', 'bid');
define('_OPTIONS23', 'Settings updated');
define('_OPTIONS24', 'Push lifetime');
define('_OPTIONS25', 'Send large image');
define('_OPTIONS26', 'Check links');
define('_OPTIONS27', 'My ads in a list');
define('_OPTIONS28', 'first');
define('_OPTIONS29', 'last');
define('_OPTIONS30', 'Days by default');
define('_OPTIONS31', 'Local time');
define('_TEST', 'Test');
define('_EDITFEED', 'Edit feed');
define('_DELETEFEED', 'Delete feed');
define('_DELETEFIELD', 'Record deleted');
define('_UPDATEFIELD', 'Record updated');
define('_INSERTFIELD', 'Record added');
define('_FEEDSTEXT1', 'Fill in all required fields highlighted');
define('_ADDFEED', 'Add feed');
define('_SENDEDMAX', 'Max. sending');
define('_SENDEDALL', 'Sended');
define('_RATE', 'Rate');
define('_STATUSON', 'On');
define('_STATUSOFF', 'Off');
define('_DASHBOARD', 'Dashboard');
define('_SUBSCRIBERS', 'Subscribers');
define('_SUBSCRIBERS2', 'Subscribers');
define('_SUBSCRIBERS3', 'Subscriber');
define('_DAYSTAT', 'By days');
define('_SENDED', 'Sended');
define('_UNIQSENDED', 'Unic. sended');
define('_SENDEDUSER', 'sending to subscriber');
define('_CLICKS', 'Clicks');
define('_SITESSTAT', 'By sites');
define('_ADVSTAT', 'By ads');
define('_FEEDSTAT', 'By feeds');
define('_REGIONSTAT', 'By regions');
define('_OSTAT', 'By OS');
define('_OS', 'OS');
define('_BROWSERSTAT', 'By browsers');
define('_NETWORKSTAT', 'By subnetworks');
define('_NETWORK', 'Subnetwork');
define('_BRANDTAT', 'By device model');
define('_MODEL', 'Model');
define('_BROWSER', 'Browser');
define('_DEVICESTAT', 'By devices');
define('_TYPE', 'Type');
define('_GROUPSTAT', 'By group');
define('_OPTIONS', 'Settings');
define('_SITES', 'Sites');
define('_STAT', 'Statistics');
define('_FEEDS', 'Feeds');
define('_DATE', 'Date');
define('_FAILURE', 'Failures');
define('_UNSUBSCRIBERS', 'Unsubs');
define('_SENDEDBYUSER', 'Sent per user');
define('_CLICKPRICE', 'Click price');
define('_MONEY', 'Earned');
define('_REQUEST', 'Requests');
define('_DATEFROM', 'Date from');
define('_TILL', 'till');
define('_FROM', 'from');
define('_SITE', 'Site');
define('_LANDING', 'Landing');
define('_SEARCH', 'Search');
define('_RESET', 'Reset');
define('_ALL', 'Total');
define('_ACTIVE', 'Actice');
define('_ACTIVEPROC', '%Act.');
define('_ALLINFO', 'General info');
define('_SUBSCRIBERSALL', 'Total subscribers');
define('_SUBSCRIBERSALLACTIVE', 'Active subscribers');
define('_UNSUBSCRIBERSALL', 'Unsubscribed');
define('_FROMALL', 'from all');
define('_LASTSUB', 'last subscription');
define('_ADDED', 'Added');
define('_UPDATE', 'Updated');
define('_ADV', 'Ad');
define('_ADV2', 'Ad');
define('_FEED', 'Feed');
define('_TITLE', 'Title');
define('_DESCR', 'Description');
define('_LINK', 'Link');
define('_EMPTY', 'Empty');
define('_AVG', 'Avg');
define('_TIME', 'Time');
define('_SEK', 'Sec.');
define('_REGION', 'Region');
define('_REGIONS', 'Regions');
define('_SUBS', 'Subscription');
define('_SHOWIMG', 'Show image');
define('_UNSUBS', 'Unsubscriptions');
define('_REGIONS_TEXT1', 'Earnings, percent per region');
define('_REFERER', 'Source');
define('_STATUS', 'Status');
define('_EVERY', 'every');
define('_STATUSACTIVE', 'active');
define('_STATUSUNSUBS', 'unsubscribed');
define('_SOURCE', 'Source');
define('_DELETED', 'Deleted');
define('_ACTIVE2', 'Active');
define('_EMPTYFEED', 'empty feed');
define('_SENDED2', 'sended');
define('_CLICKS2', 'clicks');
define('_CONV', 'Conversions');
define('_POSITION', 'Position');
define('_ALLADVS', 'Total ads.');
define('_HOURS', 'Hours passed');
define('_COMMENT', 'Comments');
define('_SENDED3', 'Sent');
define('_CLICK', 'Click');
define('_H', 'hr.');
define('_M', 'min.');
define('_TIMEFROMSEND', 'From sending time');
define('_NAME', 'Name');
define('_ADDSITE', 'Add site');
define('_ADD', 'Add');
define('_ADDNEW', 'Add new');
define('_CANCEL', 'Cancel');
define('_SEND', 'Send');
define('_ADDSITETEXT1', 'Add site name');
define('_ADDSITETEXT2', 'add site URL');
define('_ADDSITETEXT3', 'Site added');
define('_DELETESITE', 'Delete site');
define('_DELETE', 'Delete');
define('_COPY', 'Copy');
define('_PROXY', 'Proxy');
define('_EDITOR', 'Editor');
define('_PAGEURL', 'Page URL');
define('_COPYING', 'Ccpying');
define('_DELETEALL', 'Delete all');
define('_DELETESITE1', 'Delete site');
define('_DELETESITE2', 'Confirm site delete');
define('_EDIT', 'Edit');
define('_EDITSITE', 'Edit site');
define('_UPDATESITE', 'Site updated');
define('_GETCODE', 'Get code');
define('_GETCODE2', 'Site codes');
define('_CODETEXT1', 'additional source identifier');
define('_CODETEXT3', 'pause before displaying the notification in MS');
define('_CODETEXT4', '1 - close the site with a message on the subscription');
define('_CODETEXT5', '1 - display X to close the block');
define('_CODETEXT6', 'the text in the closing block');
define('_CODETEXT7', 'Also download and flow the root of the site file');
define('_CODETEXT8', ' set the code to site body, the page sould contain the head tag.');
define('_CODETEXT9', 'The code displays an information block on top of the site with an offer to subscribe for updates. When the confirmation displays a pop-up with our domain for the subscription. Code set in body, above content:');
define('_CODETEXT10', 'Put this part below:');
define('_CODETEXT11', 'Stay up to date with the latest events, subscribe to site updates');
define('_CODETEXT12', 'Subscribe');
define('_CODETEXT13', 'Сancel');
define('_CODETEXT14', ' Https only. This code allows you to block some content on the site, such as the text of the article or links to files, video player, etc. through subscription. Once subscribed, content is no longer blocked on the site. If the user has unsubscribed, he will be given instructions on how to subscribe again. Code set in body, above content:');
define('_CODETEXT15', 'Put this piece of content instead the displyed one you want to hide:');
define('_CODETEXT16', 'SITE CONTENT HERE');
define('_CODETEXT17', 'To view content subscribe to site updates');
define('_CODETEXT18', 'The code allows you to redirect users to a site or file through an intermediate page with subscription. Suitable for http sites. The user will not be able to follow the link until he or she subscribes.');
define('_CODETEXT19', 'resubscriptions for click-throughs');
define('_CODETEXT20', 'hex page background color, with no #');
define('_CODETEXT21', 'text on the page below the main text');
define('_CODETEXT22', 'template type, 0 - click the link, 1 - watch the video, 2 - download the file, 3 - confirm your age');
define('_CODETEXT23', 'set the code in body, above the elements for which redirect rule works.');
define('_CODETEXT24', 'Continue to specify for link <b class=red>class="redirect-link"</b>, or enter the link unit in <b class=red>&lt;div id="push_links"&gt;...&lt;/div&gt;</b> for all links in the block would lead through a redirect. ');
define('_CODETEXT25', 'subscriber tag');
